apiVersion: v2
appVersion: '1.0'
description: A Helm chart for cmc ccd domain
name: cmc-ccd-domain
home: https://github.com/hmcts/cmc-ccd-domain
version: 0.0.1
dependencies:
  - name: nodejs
    version: 3.0.3
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: claim-store
    version: 4.1.53
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'