apiVersion: v2
appVersion: '1.0'
description: A Helm chart for cmc ccd domain
name: cmc-ccd-domain
home: https://github.com/hmcts/cmc-ccd-domain
version: 0.0.2
dependencies:
  - name: nodejs
    version: 3.1.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'