nodejs:
  applicationPort: 3000
  autoscaling: # Default is false
    enabled: true
    maxReplicas: 5 # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization

cmc-claim-store:
  enabled: false

ccd:
  enabled: false

idam-pr:
  enabled: false

xui-webapp:
  enabled: false
