cmc-claim-store:
  java:
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/cmc/claim-store:latest
    releaseNameOverride: ${SERVICE_NAME}-claim-store
    ingressHost: claim-store-${SERVICE_FQDN}
    readinessDelay: 250  # ccd-stack will start much slower
    livenessDelay:  250  # ccd-stack will start much slower
    keyVaults:
      cmc:
        resourceGroup: cmc
        secrets:
          - name: claim-store-db-password
            alias: CLAIM_STORE_DB_PASSWORD
          - name: AppInsightsInstrumentationKey
            alias: azure.application-insights.instrumentation-key
          - name: cmc-db-password-v15
            alias: CMC_DB_PASSWORD
          - name: cmc-db-username-v15
            alias: CMC_DB_USERNAME
          - name: cmc-db-host-v15
            alias: CMC_DB_HOST
          - name: citizen-oauth-client-secret
            alias: oauth2.client.secret
          - name: claim-store-s2s-secret
            alias: idam.s2s-auth.totp_secret
          - name: anonymous-caseworker-username
            alias: idam.caseworker.anonymous.username
          - name: anonymous-caseworker-password
            alias: idam.caseworker.anonymous.password
          - name: system-update-username
            alias: idam.caseworker.system.username
          - name: system-update-password
            alias: idam.caseworker.system.password
          - name: notify-api-key
            alias: GOV_NOTIFY_API_KEY
          - name: milo-recipient
            alias: MILO_CSV_RECIPIENT
          - name: staff-email
            alias: staff-notifications.recipient
          - name: live-support-email
            alias: live-support.recipient
          - name: rpa-email-sealed-claim
            alias: rpa.notifications.sealedClaimRecipient
          - name: rpa-email-breathing-space
            alias: rpa.notifications.breathingSpaceRecipient
          - name: rpa-email-legal-sealed-claim
            alias: rpa.notifications.legalSealedClaimRecipient
          - name: rpa-email-more-time-requested
            alias: rpa.notifications.moreTimeRequestedRecipient
          - name: rpa-email-response
            alias: rpa.notifications.responseRecipient
          - name: rpa-email-ccj
            alias: rpa.notifications.countyCourtJudgementRecipient
          - name: rpa-email-paid-in-full
            alias: rpa.notifications.paidInFullRecipient
          - name: launchDarkly-sdk-key
            alias: LAUNCH_DARKLY_SDK_KEY
          - name: sendgrid-api-key
            alias: SENDGRID_API_KEY
          - name: staff-email-legal-rep
            alias: staff-notifications.legalRecipient
          - name: appinsights-connection-string
            alias: appinsights-connection-string
    environment:
      LOG_LEVEL: DEBUG
      DOC_ASSEMBLY_URL: http://dg-docassembly-aat.service.core-compute-aat.internal
      FRONTEND_BASE_URL: https://${SERVICE_FQDN}
      RESPOND_TO_CLAIM_URL: https://${SERVICE_FQDN}/first-contact/start
      CMC_DB_HOST: "{{ .Values.postgresql.releaseNameOverride}}"
      CMC_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
      CMC_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
      CMC_DB_CONNECTION_OPTIONS: ''
      CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-ccd-data-store-api
      STAFF_NOTIFICATIONS_LEGAL_RECIPIENT: moneyclaims@justice.gov.uk
      RPA_NOTIFICATIONS_LEGALSEALEDCLAIMRECIPIENT: civilmoneyclaims+rpa-legal-claim-issued@gmail.com
      RPA_NOTIFICATIONS_BREATHINGSPACERECIPIENT: breathingSpace.auto@justice.gov.uk
      MANAGEMENT_HEALTH_MAIL_ENABLED: false
      FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
      FEATURE_TOGGLES_CTSC_ENABLED: true
      FEATURE_TOGGLES_BULK_PRINT_TRANSFER_ENABLED: true
      FEATURE_TOGGLES_STAFF_EMAILS_ENABLED: false
      FEATURE_TOGGLES_STAFF_EMAILS_ENABLED_FOR_LEGAL_REP: false
      FEATURE_TOGGLES_SECURE_DOC_STORE_ENABLED: true
      FEATURE_TOGGLES_BREATHING_SPACE: true
      FEATURE_AUTO_CANCEL_PAYMENTS: true
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
      COURT_FINDER_API_URL: http://fact-api-aat.service.core-compute-aat.internal
      DOCUMENT_MANAGEMENT_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
    postgresql:
      enabled: true
      releaseNameOverride: ${SERVICE_NAME}-postgresql
      image:
        tag: '11.6.0'
        registry: hmctspublic.azurecr.io
        repository: imported/bitnami/postgresql
      primary:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 25m
        initdb:
          scripts:
            init.sql: |
              CREATE DATABASE cmc WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "claimstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "role_assignment" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      auth:
        username: hmcts
        password: hmcts