nodejs:
  image: hmctspublic.azurecr.io/cmc/ccd-definition-importer:latest
  applicationPort: 3000
  aadIdentityName: money-claims
  environment:
    NODE_ENV: production
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: ccd-domain
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_AUTH: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAY_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAY_RETURN_URL: https://moneyclaims.{{ .Values.global.environment }}.platform.hmcts.net
    FEES_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DRAFT_STORE_URL: http://draft-store-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CLAIM_STORE_URL: http://cmc-claim-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

  keyVaults:
    cmc:
      secrets:
        - os-postcode-lookup-api-key
        - AppInsightsInstrumentationKey
        - citizen-oauth-client-secret
        - cmc-s2s-secret
        - citizen-draft-store-primary
        - citizen-draft-store-secondary
        - citizen-cookie-encryption-key
        - staff-email
        - cmc-webchat-id
        - cmc-webchat-tenant
        - cmc-webchat-button-no-agents
        - cmc-webchat-button-agents-busy
        - cmc-webchat-button-service-closed
        - postcode-lookup-api-key
        - launchDarkly-sdk-key
        - pcq-token-key