apiVersion: v2
description: A Helm chart for cmc-ccd App
name: cmc-ccd-domain
home: https://github.com/hmcts/cmc-ccd-domain
version: 0.0.1
maintainers:
  - name: HMCTS OCMC team

dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
  - name: ccd
    version: 5.0.6
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.2.3
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: postgresql
    version: 8.9.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled